# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace] 
members = [
	"fun_tools",
	"executable_fun/cli_fun",
	"executable_fun/queens",
	"executable_fun/simple_http_server",
	"executable_fun/matrix_fun",
	"executable_fun/macros_fun"
]

