[package]
name = "matrix_fun"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fun_tools = { version = "0.1.0", path = "../../fun_tools" }
imageproc = "0.23.0"
nalgebra = "0.32.2"
